version: "3"

services:
  nextcloud:
    image: nextcloud:25.0.4
    ports:
      - 127.0.0.1:80:80
    user: 1000:1000
    volumes:
      - "$PWD/docker/config:/var/www/html/config"
      - "$PWD/docker/data:/var/www/html/data"
      - "$PWD/docker/apps:/var/www/html/custom_apps"
      - "$PWD:/var/www/html/custom_apps/ssi_login"