version: "3"

services:
  nextcloud:
    build: .
    ports:
      - 127.0.0.1:80:80
    user: 1000:1000
    environment:
      - PORT=80
    sysctls:
        - "kernel.msgmnb=65536"
        - "kernel.msgmax=65536"
    volumes:
      - "$PWD/docker/config:/var/www/html/config"
      - "$PWD/docker/data:/var/www/html/data"
      - "$PWD/docker/apps:/var/www/html/custom_apps"
      - "$PWD:/var/www/html/custom_apps/ssi_login"
  
  verification-service:
    image: verification-service
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - BEARER_TOKEN_SECRET=sdzaZdlsOD50VuI8XwIFF8JaEq4gID
      